services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: documental_frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    networks:
      - documental

networks:
  documental:
    external: true
    name: documental

